In [13]:
import pandas as pd
import numpy as np

/var/folders/fb/xl0hnskx527bfqkv38l3sn7h0000gn/T/ipykernel_8081/2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# df iterate rows and columns

In [14]:
df = pd.DataFrame(np.random.rand(100).reshape(10,10), columns = 'a b c d e f g h i j'.split())

In [15]:
df

,a,b,c,d,e,f,g,h,i,j
0,0.465749,0.132517,0.025900,0.074704,0.446616,0.285196,0.868134,0.806080,0.168871,0.510437
1,0.411215,0.519175,0.329177,0.329380,0.121409,0.873735,0.164294,0.816690,0.962617,0.871293
2,0.589463,0.792473,0.959527,0.496491,0.927519,0.034878,0.663285,0.945176,0.559783,0.051119
3,0.474518,0.488593,0.988484,0.389849,0.722825,0.143079,0.610211,0.793217,0.980604,0.078242
4,0.035514,0.299014,0.677290,0.068022,0.257460,0.872113,0.797633,0.307061,0.563316,0.025719
5,0.092750,0.218053,0.336194,0.385316,0.114767,0.985175,0.720408,0.705649,0.808966,0.779850
6,0.217315,0.666852,0.637054,0.524555,0.337580,0.542780,0.244752,0.623314,0.005194,0.718667
7,0.547964,0.648333,0.361368,0.464897,0.995255,0.955622,0.103602,0.392463,0.993052,0.998505
8,0.234745,0.371161,0.228211,0.692535,0.269970,0.093683,0.588095,0.572120,0.329725,0.355959
9,0.470919,0.184226,0.857123,0.884460,0.554344,0.614009,0.736092,0.869616,0.236050,0.123488

# df1 - groupby sum()

In [49]:
keys = np.array([
        ['A', 'B'],
        ['A', 'B'],
        ['A', 'B'],
        ['A', 'B"B'],
        ['C', 'D'],
        ['C', 'D'],
        ['C', 'DD'],
        ['E', 'F'],
        ['E', 'FF'],
        ['G', 'H'] 
        ])

In [50]:
df1 = pd.DataFrame(keys, columns = ['A', 'B']).join(df)
df1

,A,B,a,b,c,d,e,f,g,h,i,j
0,A,B,0.465749,0.132517,0.025900,0.074704,0.446616,0.285196,0.868134,0.806080,0.168871,0.510437
1,A,B,0.411215,0.519175,0.329177,0.329380,0.121409,0.873735,0.164294,0.816690,0.962617,0.871293
2,A,B,0.589463,0.792473,0.959527,0.496491,0.927519,0.034878,0.663285,0.945176,0.559783,0.051119
3,A,"B""B",0.474518,0.488593,0.988484,0.389849,0.722825,0.143079,0.610211,0.793217,0.980604,0.078242
4,C,D,0.035514,0.299014,0.677290,0.068022,0.257460,0.872113,0.797633,0.307061,0.563316,0.025719
5,C,D,0.092750,0.218053,0.336194,0.385316,0.114767,0.985175,0.720408,0.705649,0.808966,0.779850
6,C,DD,0.217315,0.666852,0.637054,0.524555,0.337580,0.542780,0.244752,0.623314,0.005194,0.718667
7,E,F,0.547964,0.648333,0.361368,0.464897,0.995255,0.955622,0.103602,0.392463,0.993052,0.998505
8,E,FF,0.234745,0.371161,0.228211,0.692535,0.269970,0.093683,0.588095,0.572120,0.329725,0.355959
9,G,H,0.470919,0.184226,0.857123,0.884460,0.554344,0.614009,0.736092,0.869616,0.236050,0.123488

In [51]:
export_df = df1.groupby(by = ['A', 'B']).sum()
export_df

              a         b         c         d         e         f         g  \
A B
A B    1.466428  1.444165  1.314604  0.900576  1.495544  1.193809  1.695714
  B"B  0.474518  0.488593  0.988484  0.389849  0.722825  0.143079  0.610211
C D    0.128264  0.517068  1.013484  0.453338  0.372227  1.857289  1.518041
  DD   0.217315  0.666852  0.637054  0.524555  0.337580  0.542780  0.244752
E F    0.547964  0.648333  0.361368  0.464897  0.995255  0.955622  0.103602
  FF   0.234745  0.371161  0.228211  0.692535  0.269970  0.093683  0.588095
G H    0.470919  0.184226  0.857123  0.884460  0.554344  0.614009  0.736092

              h         i         j
A B
A B    2.567945  1.691271  1.432849
  B"B  0.793217  0.980604  0.078242
C D    1.012709  1.372283  0.805569
  DD   0.623314  0.005194  0.718667
E F    0.392463  0.993052  0.998505
  FF   0.572120  0.329725  0.355959
G H    0.869616  0.236050  0.123488

In [52]:
export_df.index

MultiIndex([('A',   'B'),
            ('A', 'B"B'),
            ('C',   'D'),
            ('C',  'DD'),
            ('E',   'F'),
            ('E',  'FF'),
            ('G',   'H')],
           names=['A', 'B'])

In [53]:
export_df.index.names

FrozenList(['A', 'B'])

In [54]:
[print(dict(zip(export_df.index.names, i))) for i in export_df.index]

{'A': 'A', 'B': 'B'}
{'A': 'A', 'B': 'B"B'}
{'A': 'C', 'B': 'D'}
{'A': 'C', 'B': 'DD'}
{'A': 'E', 'B': 'F'}
{'A': 'E', 'B': 'FF'}
{'A': 'G', 'B': 'H'}

[None, None, None, None, None, None, None]

In [55]:
# sloupce pro export do csv
fieldnames = export_df.index.names + export_df.columns.to_list()
fieldnames

FrozenList(['A', 'B', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [56]:
# řádky pro export do csv
[i for i in zip(export_df.index.names, export_df.index[0])]

[('A', 'A'), ('B', 'B')]

In [57]:
[i for i in zip(export_df.columns, export_df.iloc[0])]

[('a', 1.4664276885990284),
 ('b', 1.4441651297017684),
 ('c', 1.3146041477578736),
 ('d', 0.9005757426498078),
 ('e', 1.4955436917030698),
 ('f', 1.193809292107686),
 ('g', 1.6957135873654463),
 ('h', 2.5679451700062774),
 ('i', 1.6912709101105978),
 ('j', 1.4328487181484144)]

In [58]:
# to samé lze přes .items()
[i for i in export_df.iloc[0].items()]

[('a', 1.4664276885990284),
 ('b', 1.4441651297017684),
 ('c', 1.3146041477578736),
 ('d', 0.9005757426498078),
 ('e', 1.4955436917030698),
 ('f', 1.193809292107686),
 ('g', 1.6957135873654463),
 ('h', 2.5679451700062774),
 ('i', 1.6912709101105978),
 ('j', 1.4328487181484144)]

In [59]:
# .items() vrací stejně zip
export_df.iloc[0].items()

In [60]:
# dohromady index a řádky - sečíst listy
# export_df.index[0], pak se bude místo toho iterovat přes index
[i for i in zip(export_df.index.names, export_df.index[0])] + [i for i in export_df.loc[export_df.index[0]].items()]

[('A', 'A'),
 ('B', 'B'),
 ('a', 1.4664276885990284),
 ('b', 1.4441651297017684),
 ('c', 1.3146041477578736),
 ('d', 0.9005757426498078),
 ('e', 1.4955436917030698),
 ('f', 1.193809292107686),
 ('g', 1.6957135873654463),
 ('h', 2.5679451700062774),
 ('i', 1.6912709101105978),
 ('j', 1.4328487181484144)]

In [61]:
for index in export_df.index:
    print([i for i in zip(export_df.index.names, index)] + [i for i in export_df.loc[index].items()])

[('A', 'A'), ('B', 'B'), ('a', 1.4664276885990284), ('b', 1.4441651297017684), ('c', 1.3146041477578736), ('d', 0.9005757426498078), ('e', 1.4955436917030698), ('f', 1.193809292107686), ('g', 1.6957135873654463), ('h', 2.5679451700062774), ('i', 1.6912709101105978), ('j', 1.4328487181484144)]
[('A', 'A'), ('B', 'B"B'), ('a', 0.4745184071113484), ('b', 0.4885926201831928), ('c', 0.9884838868397638), ('d', 0.3898487747852719), ('e', 0.7228246258575383), ('f', 0.14307920527809792), ('g', 0.610211426665417), ('h', 0.7932174402203327), ('i', 0.9806043078396621), ('j', 0.07824207758050372)]
[('A', 'C'), ('B', 'D'), ('a', 0.12826400663977666), ('b', 0.5170675914085444), ('c', 1.013483991082299), ('d', 0.4533377817750679), ('e', 0.3722267805949919), ('f', 1.857288505347902), ('g', 1.5180411533777773), ('h', 1.0127094941908195), ('i', 1.372282775619729), ('j', 0.8055692334113821)]
[('A', 'C'), ('B', 'DD'), ('a', 0.2173150685895915), ('b', 0.6668518965448152), ('c', 0.6370537485395725), ('d', 0.5245546091667348), ('e', 0.33757987409662027), ('f', 0.5427800483519393), ('g', 0.2447518207124364), ('h', 0.623313982364621), ('i', 0.005193989889423434), ('j', 0.7186672870808963)]
[('A', 'E'), ('B', 'F'), ('a', 0.547963770194453), ('b', 0.648333008793986), ('c', 0.3613681089457358), ('d', 0.4648969127251046), ('e', 0.9952551920942105), ('f', 0.9556216903999393), ('g', 0.10360228789593573), ('h', 0.39246315054402003), ('i', 0.993052156500162), ('j', 0.9985047111618851)]
[('A', 'E'), ('B', 'FF'), ('a', 0.23474535677284825), ('b', 0.3711605026406942), ('c', 0.22821123196077087), ('d', 0.6925353820119555), ('e', 0.26997010462339843), ('f', 0.09368254113180596), ('g', 0.588094553618947), ('h', 0.5721202965015307), ('i', 0.3297252531024699), ('j', 0.35595920958509086)]
[('A', 'G'), ('B', 'H'), ('a', 0.4709191921632707), ('b', 0.18422557946392015), ('c', 0.8571226744792856), ('d', 0.8844603265779312), ('e', 0.5543444930058855), ('f', 0.61400902822684), ('g', 0.7360919463782097), ('h', 0.869615768138907), ('i', 0.2360501838236858), ('j', 0.12348810281065559)]

In [62]:
# pro csv writer potřebuju dict

for index in export_df.index:
    print({k:v for k,v in [i for i in zip(export_df.index.names, index)] + [i for i in export_df.loc[index].items()]})

{'A': 'A', 'B': 'B', 'a': 1.4664276885990284, 'b': 1.4441651297017684, 'c': 1.3146041477578736, 'd': 0.9005757426498078, 'e': 1.4955436917030698, 'f': 1.193809292107686, 'g': 1.6957135873654463, 'h': 2.5679451700062774, 'i': 1.6912709101105978, 'j': 1.4328487181484144}
{'A': 'A', 'B': 'B"B', 'a': 0.4745184071113484, 'b': 0.4885926201831928, 'c': 0.9884838868397638, 'd': 0.3898487747852719, 'e': 0.7228246258575383, 'f': 0.14307920527809792, 'g': 0.610211426665417, 'h': 0.7932174402203327, 'i': 0.9806043078396621, 'j': 0.07824207758050372}
{'A': 'C', 'B': 'D', 'a': 0.12826400663977666, 'b': 0.5170675914085444, 'c': 1.013483991082299, 'd': 0.4533377817750679, 'e': 0.3722267805949919, 'f': 1.857288505347902, 'g': 1.5180411533777773, 'h': 1.0127094941908195, 'i': 1.372282775619729, 'j': 0.8055692334113821}
{'A': 'C', 'B': 'DD', 'a': 0.2173150685895915, 'b': 0.6668518965448152, 'c': 0.6370537485395725, 'd': 0.5245546091667348, 'e': 0.33757987409662027, 'f': 0.5427800483519393, 'g': 0.2447518207124364, 'h': 0.623313982364621, 'i': 0.005193989889423434, 'j': 0.7186672870808963}
{'A': 'E', 'B': 'F', 'a': 0.547963770194453, 'b': 0.648333008793986, 'c': 0.3613681089457358, 'd': 0.4648969127251046, 'e': 0.9952551920942105, 'f': 0.9556216903999393, 'g': 0.10360228789593573, 'h': 0.39246315054402003, 'i': 0.993052156500162, 'j': 0.9985047111618851}
{'A': 'E', 'B': 'FF', 'a': 0.23474535677284825, 'b': 0.3711605026406942, 'c': 0.22821123196077087, 'd': 0.6925353820119555, 'e': 0.26997010462339843, 'f': 0.09368254113180596, 'g': 0.588094553618947, 'h': 0.5721202965015307, 'i': 0.3297252531024699, 'j': 0.35595920958509086}
{'A': 'G', 'B': 'H', 'a': 0.4709191921632707, 'b': 0.18422557946392015, 'c': 0.8571226744792856, 'd': 0.8844603265779312, 'e': 0.5543444930058855, 'f': 0.61400902822684, 'g': 0.7360919463782097, 'h': 0.869615768138907, 'i': 0.2360501838236858, 'j': 0.12348810281065559}

In [63]:
import csv

export_df = df1.groupby(by = ['A', 'B']).sum()

with open(file = 'export_df_writer.csv', mode = 'w', newline='', encoding='utf-8',) as csvfile:
    fieldnames = export_df.index.names + export_df.columns.to_list()
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter='\t', quotechar='"', quoting=csv.QUOTE_NONNUMERIC) #quoting=csv.QUOTE_MINIMAL)
    writer.writeheader()
    for index in export_df.index:
        writer.writerow({k:v for k,v in [i for i in zip(export_df.index.names, index)] + [i for i in export_df.loc[index].items()]})

In [64]:
import csv

with open(file = 'export_df_writer.csv', mode = 'r', encoding='utf-8',) as csvfile:
    reader = csv.DictReader(csvfile, delimiter='\t', quotechar='"')
    fieldnames = reader.fieldnames
    print('Fieldnames:', fieldnames, sep='\n')
    print('Rows:')
    line = next(reader)
    while True:
        print(line)
        try:
            line = next(reader)
        except Exception as e:
            print(e)
            break

Fieldnames:
['A', 'B', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Rows:
{'A': 'A', 'B': 'B', 'a': '1.4664276885990284', 'b': '1.4441651297017684', 'c': '1.3146041477578736', 'd': '0.9005757426498078', 'e': '1.4955436917030698', 'f': '1.193809292107686', 'g': '1.6957135873654463', 'h': '2.5679451700062774', 'i': '1.6912709101105978', 'j': '1.4328487181484144'}
{'A': 'A', 'B': 'B"B', 'a': '0.4745184071113484', 'b': '0.4885926201831928', 'c': '0.9884838868397638', 'd': '0.3898487747852719', 'e': '0.7228246258575383', 'f': '0.14307920527809792', 'g': '0.610211426665417', 'h': '0.7932174402203327', 'i': '0.9806043078396621', 'j': '0.07824207758050372'}
{'A': 'C', 'B': 'D', 'a': '0.12826400663977666', 'b': '0.5170675914085444', 'c': '1.013483991082299', 'd': '0.4533377817750679', 'e': '0.3722267805949919', 'f': '1.857288505347902', 'g': '1.5180411533777773', 'h': '1.0127094941908195', 'i': '1.372282775619729', 'j': '0.8055692334113821'}
{'A': 'C', 'B': 'DD', 'a': '0.2173150685895915', 'b': '0.6668518965448152', 'c': '0.6370537485395725', 'd': '0.5245546091667348', 'e': '0.33757987409662027', 'f': '0.5427800483519393', 'g': '0.2447518207124364', 'h': '0.623313982364621', 'i': '0.005193989889423434', 'j': '0.7186672870808963'}
{'A': 'E', 'B': 'F', 'a': '0.547963770194453', 'b': '0.648333008793986', 'c': '0.3613681089457358', 'd': '0.4648969127251046', 'e': '0.9952551920942105', 'f': '0.9556216903999393', 'g': '0.10360228789593573', 'h': '0.39246315054402003', 'i': '0.993052156500162', 'j': '0.9985047111618851'}
{'A': 'E', 'B': 'FF', 'a': '0.23474535677284825', 'b': '0.3711605026406942', 'c': '0.22821123196077087', 'd': '0.6925353820119555', 'e': '0.26997010462339843', 'f': '0.09368254113180596', 'g': '0.588094553618947', 'h': '0.5721202965015307', 'i': '0.3297252531024699', 'j': '0.35595920958509086'}
{'A': 'G', 'B': 'H', 'a': '0.4709191921632707', 'b': '0.18422557946392015', 'c': '0.8571226744792856', 'd': '0.8844603265779312', 'e': '0.5543444930058855', 'f': '0.61400902822684', 'g': '0.7360919463782097', 'h': '0.869615768138907', 'i': '0.2360501838236858', 'j': '0.12348810281065559'}

In [67]:
export_df = df1.groupby(by = ['A', 'B']).sum()
export_df.to_csv('export_df_bez_writer.csv', sep='\t') #používá quoting=csv.QUOTE_MINIMAL

In [68]:
import csv

with open(file = 'export_df_bez_writer.csv', mode = 'r', encoding='utf-8',) as csvfile:
    reader = csv.DictReader(csvfile, delimiter='\t', quotechar='"')
    fieldnames = reader.fieldnames
    print('Fieldnames:', fieldnames, sep='\n')
    print('Rows:')
    line = next(reader)
    while True:
        print(line)
        try:
            line = next(reader)
        except Exception as e:
            print(e)
            break

Fieldnames:
['A', 'B', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Rows:
{'A': 'A', 'B': 'B', 'a': '1.4664276885990284', 'b': '1.4441651297017684', 'c': '1.3146041477578736', 'd': '0.9005757426498078', 'e': '1.4955436917030698', 'f': '1.193809292107686', 'g': '1.6957135873654463', 'h': '2.5679451700062774', 'i': '1.6912709101105978', 'j': '1.4328487181484144'}
{'A': 'A', 'B': 'B"B', 'a': '0.4745184071113484', 'b': '0.4885926201831928', 'c': '0.9884838868397638', 'd': '0.3898487747852719', 'e': '0.7228246258575383', 'f': '0.14307920527809792', 'g': '0.610211426665417', 'h': '0.7932174402203327', 'i': '0.9806043078396621', 'j': '0.07824207758050372'}
{'A': 'C', 'B': 'D', 'a': '0.12826400663977666', 'b': '0.5170675914085444', 'c': '1.013483991082299', 'd': '0.4533377817750679', 'e': '0.3722267805949919', 'f': '1.857288505347902', 'g': '1.5180411533777773', 'h': '1.0127094941908195', 'i': '1.372282775619729', 'j': '0.8055692334113821'}
{'A': 'C', 'B': 'DD', 'a': '0.2173150685895915', 'b': '0.6668518965448152', 'c': '0.6370537485395725', 'd': '0.5245546091667348', 'e': '0.33757987409662027', 'f': '0.5427800483519393', 'g': '0.2447518207124364', 'h': '0.623313982364621', 'i': '0.005193989889423434', 'j': '0.7186672870808963'}
{'A': 'E', 'B': 'F', 'a': '0.547963770194453', 'b': '0.648333008793986', 'c': '0.3613681089457358', 'd': '0.4648969127251046', 'e': '0.9952551920942105', 'f': '0.9556216903999393', 'g': '0.10360228789593573', 'h': '0.39246315054402003', 'i': '0.993052156500162', 'j': '0.9985047111618851'}
{'A': 'E', 'B': 'FF', 'a': '0.23474535677284825', 'b': '0.3711605026406942', 'c': '0.22821123196077087', 'd': '0.6925353820119555', 'e': '0.26997010462339843', 'f': '0.09368254113180596', 'g': '0.588094553618947', 'h': '0.5721202965015307', 'i': '0.3297252531024699', 'j': '0.35595920958509086'}
{'A': 'G', 'B': 'H', 'a': '0.4709191921632707', 'b': '0.18422557946392015', 'c': '0.8571226744792856', 'd': '0.8844603265779312', 'e': '0.5543444930058855', 'f': '0.61400902822684', 'g': '0.7360919463782097', 'h': '0.869615768138907', 'i': '0.2360501838236858', 'j': '0.12348810281065559'}